/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
  ],
  theme: {
    extend: {
      colors: {
        // Forest design tokens (Material 3 based, from stitch design)
        primary: "#012d1d",
        "on-primary": "#ffffff",
        "primary-container": "#1b4332",
        "on-primary-container": "#86af99",
        "primary-fixed": "#c1ecd4",
        "primary-fixed-dim": "#a5d0b9",
        "on-primary-fixed": "#002114",
        "on-primary-fixed-variant": "#274e3d",
        "inverse-primary": "#a5d0b9",
        secondary: "#0e6c4a",
        "on-secondary": "#ffffff",
        "secondary-container": "#a0f4c8",
        "on-secondary-container": "#19724f",
        "secondary-fixed": "#a0f4c8",
        "secondary-fixed-dim": "#85d7ad",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        tertiary: "#302410",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#473a24",
        "on-tertiary-container": "#b7a487",
        "tertiary-fixed": "#f6dfc0",
        "tertiary-fixed-dim": "#d9c4a5",
        "on-tertiary-fixed": "#251a07",
        "on-tertiary-fixed-variant": "#53452e",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        surface: "#f9f9f8",
        "on-surface": "#191c1c",
        "surface-dim": "#d9dad9",
        "surface-bright": "#f9f9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f3",
        "surface-container": "#edeeed",
        "surface-container-high": "#e7e8e7",
        "surface-container-highest": "#e1e3e2",
        "on-surface-variant": "#414844",
        "surface-variant": "#e1e3e2",
        "inverse-surface": "#2e3131",
        "inverse-on-surface": "#f0f1f0",
        outline: "#717973",
        "outline-variant": "#c1c8c2",
        "surface-tint": "#3f6653",
        background: "#f9f9f8",
        "on-background": "#191c1c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
      },
      spacing: {
        "container-max-width": "1200px",
        gutter: "24px",
        unit: "8px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      boxShadow: {
        nature: "0 4px 12px rgba(27, 67, 50, 0.05)",
        "nature-lg": "0 12px 30px rgba(27, 67, 50, 0.08)",
        "nature-xl": "0 10px 30px -5px rgba(27, 67, 50, 0.05), 0 4px 6px -2px rgba(27, 67, 50, 0.03)",
      },
    },
  },
  plugins: [],
};
